#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create RDS subnet "

#debug block
  ./showENV.sh
#

#
 RDSsubnet2=$(aws ec2 create-subnet --vpc-id "${VpcId}" --cidr-block "${RDS2cidr}" --availability-zone ${RDS2azone} | grep 'SubnetId' | cut -d':' -f2 | tr -d '"| |,')

 # New Naming Standards
  aws ec2 create-tags --resources "${RDSsubnet2}" --tags Key=Name,Value=${MajorTag}-${MinorTag}-rds2-${RDS2azone}-sn

echo ${RDSsubnet2} >> ${VpcId}-build-log.json
 aws ec2 describe-subnets --subnet-ids ${RDSsubnet2} >> ${VpcId}-build-log.json

# update creatCFG file
echo "export RDSnet2=${RDSsubnet2}" >> ${build_CFG}

echo "Select Availability Zone" >> ${VpcId}-build-log.json
RDS2azone=$(aws ec2 describe-subnets --subnet-ids ${RDSsubnet2} | grep AvailabilityZone | cut -d':' -f2 | tr -d '"| |,')

# update creatCFG file
  echo "export RDS2azone=${RDS2azone}" >> ${build_CFG}

# fin 0
