#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create RDS App Cluster "

#debug block
  ./showiENV.sh
#

# TODO - These is loging in place

# DOUBLE CHECK
# - https://processminer.atlassian.net/wiki/spaces/TEC/pages/28213258/International+Papers

# create-db-parameter-group
aws rds create-db-parameter-group \
    --db-parameter-group-name identity-grp \
    --db-parameter-group-family mysql5.7 \
    --description identity-grp \
    --tags Key=general_log,Value=1 \
           Key=innodb_lock_wait_timeout,Value=3600 \
           Key=interactive_timeout,Value=230400 \
           Key=max_allowed_packet,Value=1073741824 \
           Key=net_buffer_length,Value=1000000 | jq .
#
sleep 30

source ./createCFG.env        # be sure and source it

# create-db-subnet-group
aws rds create-db-subnet-group \
 --db-subnet-group-name ${MajoriTag}-${MinoriTag}-rds-grp \
 --db-subnet-group-description ${MajoriTag}-${MinoriTag}-rds-grp \
 --subnet-ids ${RDSinet1} ${RDSinet2} | jq .
#
sleep 30

# create-db-instance
aws rds create-db-instance \
    --db-name processminer \
    --db-instance-identifier identity \
    --db-instance-class db.t2.medium \
    --db-subnet-group-name ${MajoriTag}-${MinoriTag}-rds-grp \
    --multi-az \
    --iops 1000 \
    --publicly-accessible \
    --engine MySQL \
    --engine-version 5.7.16 \
    --allocated-storage 120 \
    --master-username ${MajoriTag}${MinoriTag}masterusr \
    --master-user-password MwwNHkUp3KMxRgM \
    --backup-retention-period 31 | jq .
  # needs to be private flag


# # create-db-instance-read-replica -- should be in diff region
#
# aws rds create-db-instance-read-replica \
#   --db-instance-identifier mydbinstance-replica \
#   --source-db-instance-identifier mydbinstance-v2 \
#   --no-publicly-accessible \
#   --storage-type standard \
#   --db-instance-class db.t2.medium \
#   --db-subnet-group-name test-db-subnet | jq .
#
#

# fin 0
