#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create PRIVATE subnet "

#debug block
  ./showiENV.sh
#

#
privateSub2=$(aws ec2 create-subnet --vpc-id "${VpciId}" --cidr-block "${PRV2icidr}" --availability-zone ${PRV2iazone} | grep 'SubnetId' | cut -d':' -f2 | tr -d '"| |,')

 # New Naming Standards
  aws ec2 create-tags --resources ${privateiSub2} --tags Key=Name,Value=${MajoriTag}-${MinoriTag}-prv2-${PRV2iazone}-sn

echo ${privateiSub2} >> ${VpciId}-build-log.json
aws ec2 describe-subnets --subnet-ids ${privateiSub2} >> ${VpciId}-build-log.json

# update creatCFG file
echo "export PRVnet2=${privateiSub2}" >> ${build_CFG}

echo "Select Availability Zone" >> ${VpciId}-build-log.json
AZone2=$(aws ec2 describe-subnets --subnet-ids ${privateiSub2} | grep AvailabilityZone | cut -d':' -f2 | tr -d '"| |,')

# update creatCFG file
echo "export AZone2=${iAZone2}" >> ${build_CFG}

# fin 0
