#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create EC2-Public PORTAL 1"

#debug block
  ./showiENV.sh
#

EC2por1=$(aws ec2 run-instances --count 1 \
 --image-id "${EC2_ami}" \
 --instance-type "${EC2i_type}" \
 --key-name "${EC2i_keyname}" \
 --security-group-ids "${SGissh}" \
 --subnet-id "${PUBinet1}" \
 --associate-public-ip-address \
 --block-device-mappings "[{\"DeviceName\": \"/dev/sda1\",\"Ebs\":{\"VolumeSize\":100}}]" \
 --user-data file://ec2configs/public-ec2-build.sh \
 --placement AvailabilityZone="${iAZone1}" \
  | grep InstanceId | cut -d':' -f2 | tr -d '"|,| ' )

#   --user-data file://ec2configs/public-ec2-build.sh \
# work out how the sg has AvailabilityZone

#
#  workerID=$( echo {0..9}{0..9}{0..9}{0..9} | tr ' ' '\012' | gshuf | head -1 )
#
  aws ec2 create-tags --resources ${EC2por1} --tags Key=Name,Value=${MajoriTag}-${MinoriTag}-pub1-portal-${iAZone1}-ec2

# TODO - needs ec2 instance lock out and detail monitoring
