#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "create AWS-VPC"

#debug block
  ./showENV.sh
#

# aws ec2 create-vpc
VpcId=$(aws ec2 create-vpc --cidr-block ${iVPCcidr} | grep VpcId | cut -d':' -f2 | tr -d '"| |,')

# New Naming Standards
 aws ec2 create-tags --resources ${VpciId} --tags Key=Name,Value="${MajoriTag}-${MinoriTag}-vpc"

date             > ${MajoriTag}-${MinoriTag}-${VpciId}-buildlog.json
echo "${VpciId}" >> ${VpciId}-build-log.json
aws ec2 describe-vpcs >> ${VpciId}-build-log.json

echo "Modify-VOC attribute DNS attributes"
 aws ec2 modify-vpc-attribute --vpc-id "${VpciId}" --enable-dns-support "{\"Value\":true}"
 aws ec2 modify-vpc-attribute --vpc-id "${VpciId}" --enable-dns-hostnames "{\"Value\":true}"

# update creatCFG file
  echo "export VpcId=${VpciId}" >> ${build_CFG}

# fin 0;
