#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create RDS subnet "

#debug block
  ./showENV.sh
#

#
 RDSsubnet1=$(aws ec2 create-subnet --vpc-id "${VpcId}" --cidr-block "${RDS1cidr}" --availability-zone ${PRV1azone}  | grep 'SubnetId' | cut -d':' -f2 | tr -d '"| |,')
 aws ec2 create-tags --resources "${RDSsubnet1}" --tags Key=Name,Value=${VPC_stack}${VPC_envmt}-rds1-${PRV1azone}

echo ${RDSsubnet1} >> ${VpcId}-build-log.json
aws ec2 describe-subnets --subnet-ids ${RDSsubnet1} >> ${VpcId}-build-log.json

# update creatCFG file
echo "export PRVnet1=${RDSsubnet1}" >> ${build_CFG}

# no Select Availability Zone -- not sure why ??

# update creatCFG file
echo "export PRVnet1=${RDSsubnet1}" >> ${build_CFG}

echo "Select Availability Zone" >> ${VpcId}-build-log.json
AZone1=$(aws ec2 describe-subnets --subnet-ids ${RDSsubnet1} | grep AvailabilityZone | cut -d':' -f2 | tr -d '"| |,')

# update creatCFG file
echo "export AZone1=${AZone1}" >> ${build_CFG}

# fin 0
