#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017

# Load ENV parameters
source ./createCFG.env

echo "Create PUBLIC subnet"

#debug block
  ./showiENV.sh
#

 publicSub1=$(aws ec2 create-subnet --vpc-id "${VpciId}" --cidr-block ${PUB1cidr} --availability-zone ${PUB1iazone} | grep SubnetId | cut -d':' -f2 | tr -d '"| |,')

# New Naming Standards
   aws ec2 create-tags --resources ${publiciSub1} --tags Key=Name,Value=${MajoriTag}-${MinoriTag}-pub1-${PUB1iazone}-sn

echo PUBNET1 ${publiciSub1} >> ${VpciId}-build-log.json
 aws ec2 describe-subnets --subnet-ids ${publicSub1} >> ${VpciId}-build-log.json

# update creatCFG file
 echo "export PUBnet1=${publiciSub1}" >> ${build_CFG}

 echo "Select Availability Zone" >> ${VpciId}-build-log.json
 AZone1=$(aws ec2 describe-subnets --subnet-ids ${publiciSub1} | grep AvailabilityZone | cut -d':' -f2 | tr -d '"| |,')

# update creatCFG file
 echo "export AZone1=${iAZone1}" >> ${build_CFG}

# fin 0
