#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create Key Pair"

#debug block
  ./showENV.sh
#

export myACCOUNT=$(aws iam list-account-aliases | tr -d '{|}|[|]|"| |-' | egrep -v ':|^$');
export myREGION=$(aws configure list | grep region | awk '{print $2}' | tr -d '{|}|[|]|"| |-' );

# create-key-pairs
aws ec2 create-key-pair \
 --region ${AWS_DEFAULT_REGION} \
 --key-name "${myACCOUNT}-${myREGION}-${MajorTag}-${MinorTag}-${VpcId}" \
 | jq -r ".KeyMaterial" > ./${myACCOUNT}-${myREGION}-${MajorTag}-${MinorTag}-${VpcId}.pem

#  | grep KeyMaterial | cut -d':' -f2 | tr -d ',|"| |')
# echo -e ${MyKEY} > ${myACCOUNT}-${myREGION}-${VpcId}.pem

# update creatCFG file
echo "export EC2_keyname=${myACCOUNT}-${myREGION}-${MajorTag}-${MinorTag}-${VpcId}" >> ${build_CFG}

# To Show - aws ec2 describe-key-pairs
# Set Env - export MyKeyPair='MyKeyPair'
# To Kill - aws ec2 delete-key-pair --key-name ${MyKeyPair}

# {
#     "KeyFingerprint": "dc:6c:80:c9:76:2c:0e:11:41:f8:ea:a7:dd:ad:02:72:74:a0:5a:43",
#     "KeyName": "processminerarea51-useast1-vpc-6f1d2c17-mahrt-wra-qa"
# }
